# frozen_string_literal: true

FactoryBot.define do
  factory :lex_entry, traits: %i(person) do
    title { Faker::Name.name }

    # only ingested entries statuses are generated by default,
    # you can specify 'raw' explicitely if needed, but in this case it would be better to use
    # `create(:lex_file, <type>, entry_status: :raw).lex_entry` instead
    status { %w(draft published).sample }

    trait :person do
      lex_item { status.to_s == 'raw' ? nil : build(:lex_person) }
    end

    trait :publication do
      lex_item { status.to_s == 'raw' ? nil : build(:lex_publication) }
    end
  end
end
