FROM ubuntu:24.04

ADD https://github.com/jgm/pandoc/releases/download/3.8.2.1/pandoc-3.8.2.1-1-amd64.deb /tmp/pandoc.deb

RUN apt-get update -qq \
    && apt-get install -y curl cmake git wkhtmltopdf yaz libyaz-dev libmagickwand-dev \
    mysql-client libmysqlclient-dev \
    libpcap-dev libyaml-dev \
    && dpkg -i /tmp/pandoc.deb \
    && apt-get clean \
    && rm -rf /tmp/* /var/tmp/*
