# Enter your per-environment constants below

development: &default
  google_oauth_client_id: 'bla'
  google_oauth_client_secret: 'bla'
  twitter_consumer_key: 'bla'
  twitter_consumer_secret: 'bla'

production:
  <<: *default

test:
  <<: *default
