name: Delete outdated docker images

on:
  schedule:
    - cron: "0 0 * * *"  # Run daily at midnight UTC
  workflow_dispatch:     # allow manual triggering
permissions:
  packages: write
jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Delete old docker images
        uses: actions/delete-package-versions@v5
        with:
          package-name: 'bybe'
          package-type: 'container'
          ignore-versions: '^production-.+|.+-latest$'
          min-versions-to-keep: 10 # Keep 10 versions