name: "Copilot Setup Steps"

# Automatically run the setup steps when they are changed to allow for easy validation, and
# allow manual testing through the repository's "Actions" tab
on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/copilot-setup-steps.yml
  pull_request:
    paths:
      - .github/workflows/copilot-setup-steps.yml

jobs:
  # The job MUST be called `copilot-setup-steps` or it will not be picked up by Copilot.
  copilot-setup-steps:
    runs-on: ubuntu-latest
    container:
      image: damisul/bybe-base:latest
      env:
        RAILS_ENV: test
        ELASTICSEARCH_HOST: elasticsearch:9200
        DATABASE_URL: mysql2://root:root@mysql:3306/bybe_test
    services:
      mysql:
        image: mysql:8.0.36
        env:
          MYSQL_ROOT_PASSWORD: root
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
      elasticsearch:
        image: elasticsearch:7.17.8
        env:
          discovery.type: single-node
          xpack.security.enabled: false
          ingest.geoip.downloader.enabled: false
          action.destructive_requires_name: false
          ES_JAVA_OPTS: -Xms1024m -Xmx1024m
      redis:
        image: redis:7.2.3
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Verify MySQL connection from host
        run: |
          mysql --host mysql --port 3306 -uroot -proot -e "SHOW GRANTS FOR 'root'@'localhost'"
      - name: Update Configuration
        run: |
          cp ./.github/workflows/rspec_config/* ./config && rm .env.test
      - name: Setup DB
        env:
          RAILS_ENV: test
          DATABASE_URL: mysql2://root:root@mysql:3306/bybe_test
        run: |
          bin/rails db:create
          bin/rails db:migrate
